# PR Based Deploy On OpensShift
# Builds and Deploys unmerged PR's to temporary pods/services/routes/etc in the OpenShift Dev environment.
name: PR-Based Deploy on OpensShift

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # Print variables for logging and debugging purposes
  checkEnv:
    name: test
    runs-on: ubuntu-16.04
    steps:
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo $${{ github.event.pull_request }}
          echo $${{ github.event.pull_request.title }}

      
